# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='EmergencyMode',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
