# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_registers_emergencymode'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmode',
            name='TrendStarted',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
